Add allow-list config option to securitychecker_enlightn
phpro/grumphp pull request #1052
Opened 2022-11-15 09:14 UTC by peterjaap

| Q             | A
| ------------- | ---
| Branch        | master for features and deprecations
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Documented?   | no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any

See https://github.com/phpro/grumphp/discussions/1037

2022-11-15 09:27 UTC, peterjaap commented
Needs some work, I'll get back to this.

2022-11-19 16:15 UTC, peterjaap commented
@veewee done! :partying_face:

2022-11-25 08:48 UTC, veewee requested changes
Thanks for the PR!

It seems like it is not completely ready yet. Can you take a look at the remarks?

2022-11-25 08:48 UTC, veewee commented on src/Task/SecurityCheckerEnlightn.php
> +        foreach ($config['allow-list'] as $cve) {
Wouldn't it be better to 
```php
->addArgumentArray('--allow-list=%s', $config['allow-list'])
```
or is there a specific reason you want to add an optional argument?

2022-11-25 08:48 UTC, veewee commented on test/Unit/Task/SecurityCheckerEnlightnTest.php
>              ]
Can you also add test-cases covering this new argument?

2023-09-29 08:30 UTC, veewee commented
@peterjaap It's a nice feature... Care to finish up this PR? :)

2023-09-29 11:22 UTC, peterjaap commented
@veewee sure, but I've asked you some questions in the comments

2023-09-29 11:35 UTC, veewee commented
> @veewee sure, but I've asked you some questions in the comments

Is it possible you made those comments as part of a code review but did not submit those comments? I am not seeing any.

2023-09-29 11:39 UTC, peterjaap commented on src/Task/SecurityCheckerEnlightn.php
> +        foreach ($config['allow-list'] as $cve) {
I've never heard of `addArgumentArray`, I can't find documentation on `addArgumentArray` anywhere?

2023-09-29 11:39 UTC, peterjaap commented on test/Unit/Task/SecurityCheckerEnlightnTest.php
>              ]
Like which cases?

2023-09-29 11:39 UTC, peterjaap commented
@veewee woops, you're right :see_no_evil: Almost a year ago, lol.

2023-09-29 12:54 UTC, veewee commented on src/Task/SecurityCheckerEnlightn.php
> +        foreach ($config['allow-list'] as $cve) {
In your current code, you are iterating over the allow-list configuration just to add it as an argument;
Inside the `$arguments` (of type `\GrumPHP\Collection\ProcessArgumentsCollection`), there is a shortcut method `addArgumentArray()` that does this for you.
This is being used all over the repository to make the tasks easier to read.

You could use it like this:

```php
->addArgumentArray('--allow-list=%s', $config['allow-list'])
```

2023-09-29 12:54 UTC, veewee commented on test/Unit/Task/SecurityCheckerEnlightnTest.php
>              ]
The test cases should cover all options : you currently changed the default test-case, which has an empty allow list.
On top of that, a new case must be added that tests that if you pass a non-empty array to the `allow-list`, that the resulting CLI command contains one or multiple `--allow-list` flags

2024-11-26 12:40 UTC, veewee commented
We notices this PR became inactive. If you wish to continue, feel free to pick it up again.
If not, we will be closing this PR soon. Thanks for your understanding.

2024-12-13 12:16 UTC, veewee commented
Duplicate of newer PR #1161

2024-12-13 12:16 UTC, closed without merging